services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    features:
      - token-exchange
    environment:
      KC_DB: mssql
      KC_DB_URL_HOST: 10.0.0.9
      KC_DB_URL_PORT: 1435
      KC_DB_URL_DATABASE: ActiveSooperWizerNCL
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: spts@3311

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
