services:
  seaweedfs-master:
    image: chrislusf/seaweedfs
    command: master -ip=seaweedfs-master -port=9333
    ports:
      - "9333:9333"
    volumes:
      - seaweedfs-master:/data

  seaweedfs-volume:
    image: chrislusf/seaweedfs
    command: volume -mserver=seaweedfs-master:9333 -port=8080 -dir=/data
    ports:
      - "8080:8080"
    depends_on:
      - seaweedfs-master
    volumes:
      - seaweedfs-volume:/data

  seaweedfs-filer:
    image: chrislusf/seaweedfs
    command: filer -master=seaweedfs-master:9333 -port=8888
    ports:
      - "8888:8888"
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    volumes:
      - seaweedfs-filer:/data

volumes:
  seaweedfs-master:
  seaweedfs-volume:
  seaweedfs-filer:
